//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CreateInvoice
    {
        public int invoiceID { get; set; }
        [Required(ErrorMessage = "Please Enter From Address ")]
        public string fromAddress { get; set; }
        [Required(ErrorMessage = "Please Enter ToAddress")]
        public string toaddress { get; set; }

        public Nullable<int> oderid { get; set; }
        public string notes { get; set; }
        public Nullable<decimal> total { get; set; }
        [Required(ErrorMessage = "Please Mention Paid or Not")]
        public string PaidorNot { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
