//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.CreateInvoices = new HashSet<CreateInvoice>();
        }
    
        public int OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreateInvoice> CreateInvoices { get; set; }
        public virtual Order Order { get; set; }
    }
}
