//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderProduct()
        {
            this.CreateInvoices = new HashSet<CreateInvoice>();
        }
    
        public int orderId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> customerId { get; set; }
        public Nullable<System.DateTime> date_of_Order { get; set; }
        public Nullable<double> qunt { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product1 Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreateInvoice> CreateInvoices { get; set; }
    }
}
